### ISSUE TITLE
Avoid hardcoded paths in scripts

### ISSUE THREAD

**Issue by nylander** [abhijeetsingh1704/AcetoScan#99]
The `acetoscan` script has a number of lines where files are written to hardcoded paths. For example (there are several, similar cases):

```
    exec > >(tee -a "/home/${user}/acetoscan/"acetoscan_log )
    exec 2> >(tee -a "/home/${user}/acetoscan/"acetoscan_log >&2)
```

The presence of the folder `/home/${user}/acetoscan/` should be avoided, and the output files written to a(nother) folder, which can be created at run time.

Also related: issue #98

**Comment by abhijeetsingh1704** [comment]
fixed
